version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
    dns: ["8.8.8.8"]
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"

  # worker:
  #   image: renansmoreira/worker:1.0.1
  #   dns: ["8.8.8.8"]
  #   depends_on:
  #      - rabbitmq
  #   command: ['./tools/wait-for-it.sh', 'rabbitmq:5672', '--', "node", "./src/worker/src/index.js", "--amqp_uri", "amqp://admin:Phaish9ohbaidei6oole@rabbitmq"]