version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
    dns: ["8.8.8.8"]
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"

  worker:
    image: renansmoreira/worker:2.0.1
    dns: ["8.8.8.8"]
    depends_on:
       - rabbitmq
    command: ['./tools/wait-for-it.sh', 'rabbitmq:5672', '--', "python3", "-u", "src/worker/src/batch_ocr_worker.py", "--amqp_uri", "amqp://admin:Phaish9ohbaidei6oole@rabbitmq", "--fila_de_processamento", "para_processar_sed", "--fila_de_processados", "processados_sed", "--fila_de_nao_processados", "nao_processados_sed"]