apiVersion: v1
kind: ReplicationController
metadata:
  name: digix-ocr-worker
spec:
  replicas: 2
  selector:
    name: digix-ocr-worker
  template:
    metadata:
      labels:
        name: digix-ocr-worker
    spec:
      containers:
        - name: digix-ocr-worker
          image: renansmoreira/worker:2.0.0
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq-password
                  key: password
          command: ['./tools/wait-for-it.sh', '130.211.209.146:5672', '--', "python3", "src/worker/src/batch_ocr_worker.py", "--amqp_uri", "amqp://admin:$(RABBITMQ_PASSWORD)@130.211.209.146", "--fila_de_processamento", "para_processar_sed", "--fila_de_processados", "processados_sed", "--fila_de_nao_processados", "nao_processados_sed"]
