apiVersion: v1
kind: ReplicationController
metadata:
  name: digix-ocr-worker
spec:
  replicas: 1
  selector:
    name: digix-ocr-worker
  template:
    metadata:
      labels:
        name: digix-ocr-worker
    spec:
      containers:
        - name: digix-ocr-worker
          image: renansmoreira/worker:2.0.6
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq-password
                  key: password
          command: ["python3", "-u", "src/worker/src/batch_ocr_worker.py", "--amqp_uri", "amqp://admin:$(RABBITMQ_PASSWORD)@130.211.209.146", "--fila_de_processamento", "para_processar_sanesul", "--fila_de_processados", "processados_sanesul", "--url_de_download_da_imagem", "http://domusweb.dev.digix.com.br:8083/Questionario/Horus/ObterArquivos", "--fila_de_nao_processados", "nao_processados_sanesul"]
